### ISSUE TITLE
Fails to run even with source-built tkdnd

### ISSUE THREAD

**Issue by semfault** [ColdWindScholar/MIO-KITCHEN-SOURCE#105]
I've installed tkinterdnd2 and tkdnd from source and tool still complains about missing tkdnd
```
segfault@trashbox:~/mio$ ./tool
Traceback (most recent call last):
  File "src/TkinterDnD.py", line 55, in _require
_tkinter.TclError: can't find package tkdnd

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tool.py", line 8, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller/loader/pyimod02_importers.py", line 384, in exec_module
  File "src/tool.py", line 867, in <module>
  File "src/tool.py", line 605, in __init__
  File "src/TkinterDnD.py", line 287, in __init__
  File "src/TkinterDnD.py", line 57, in _require
RuntimeError: Unable to load tkdnd library.
[PYI-6357:ERROR] Failed to execute script 'tool' due to unhandled exception!
```

**Comment by ColdWindScholar** [comment]
ok

**Comment by ColdWindScholar** [comment]
fixed
