### ISSUE TITLE
Magiskboot not found

### ISSUE THREAD

**Issue by redzrush101** [ColdWindScholar/MIO-KITCHEN-SOURCE#32]
Big thanks for this tool its still awesome.
I get the error when trying to unpack vendor_boot.img under Archlinux, I have run chmod a+x ./* in all directories.
I have attached the files as a txt and this is the error code: 
Exception in thread Thread-6 (close_):
Traceback (most recent call last):
  File "threading.py", line 1016, in _bootstrap_inner
  File "threading.py", line 953, in run
  File "tool.py", line 2879, in close_
  File "tool.py", line 130, in call_func
  File "tool.py", line 2399, in unpack
  File "tool.py", line 130, in call_func
  File "tool.py", line 1997, in jboot
  File "tool.py", line 1906, in call
  File "subprocess.py", line 971, in __init__
  File "subprocess.py", line 1863, in _execute_child
FileNotFoundError: [Errno 2] No such file or directory: './bin/Linux/x86_64/magiskboot
![2024-03-24-093908_1920x1080_scrot](https://github.com/ColdWindScholar/MIO-KITCHEN-SOURCE/assets/109347215/d0e1b70b-cf1f-4ca6-9357-ff5a97df867e)
[files.txt](https://github.com/ColdWindScholar/MIO-KITCHEN-SOURCE/files/14734884/files.txt)

**Comment by ookiineko** [comment]
just wondering, did you change the working directory?

**Comment by ColdWindScholar** [comment]
fixed
