### ISSUE TITLE
cant unpack payload from redmi note 13 4g 

### ISSUE THREAD

**Issue by proganime1200** [ColdWindScholar/MIO-KITCHEN-SOURCE#43]
**Hello Good Day friend! Can you try unpacking the payload.bin of redmi note 13 4g hyperos there are some issues on my end**

The rom or firmware im using is hyper os from this website : https://miuirom.org/phones/redmi-note-13
This are the logs ive captured from your MIO-KITCHEN app:

```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "tool.py", line 2409, in unpack
  File "dumper.py", line 71, in run
MemoryError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "threading.py", line 932, in _bootstrap_inner
  File "threading.py", line 870, in run
  File "tool.py", line 3007, in close_
  File "tool.py", line 147, in call_func
  File "tool.py", line 2420, in unpack
  File "dumper.py", line 83, in run
  File "dumper.py", line 87, in multiprocess_partitions
  File "dumper.py", line 87, in <dictcomp>
  File "concurrent\futures\thread.py", line 188, in submit
  File "concurrent\futures\thread.py", line 213, in _adjust_thread_count
  File "threading.py", line 852, in start
RuntimeError: can't start new thread
```
This is the content of the rom (note 13 is the name of the project and tried to unpack the payload.bin contents by selecting all then  clicking the run button
![image](https://github.com/ColdWindScholar/MIO-KITCHEN-SOURCE/assets/32473502/c36ee529-a9cb-4c40-b028-5461ce0d6e69)

![image](https://github.com/ColdWindScholar/MIO-KITCHEN-SOURCE/assets/32473502/8684741a-4ca6-4f12-bc48-0e2e7eb73de9) 
This is the content of the rom (note 13 is the name of the project and tried to unpack the payload.bin contents by selecting all:

And btw Im using windows 10 xeon e3-1270 gtx 1050 12gb ram to run your program wishing you fixed this issue i love your program because its free and opensource.

**Comment by ColdWindScholar** [comment]
Extract the partiton one by one, dont select over four

**Comment by proganime1200** [comment]
> Extract the partiton one by one, dont select over four

Oh! Thanks so it cant extract all at the same time and the limit is four when i  tried it works btw can we generate dynamic_partitions_op_list or able to recreate zip to pack super image on it thabnks for this usefull software
