### ISSUE TITLE
vendor_boot打包失败

### ISSUE THREAD

**Issue by ymdzq** [ColdWindScholar/MIO-KITCHEN-SOURCE#45]
版本3.5.8，如果项目文件夹里已经有了boot.img就会无法打包vendor_boot.img报错，
如果删除boot.img，打包vendor_boot会生成boot.img而不是vendor_boot.img

Exception in thread Thread-17:
Traceback (most recent call last):
  File "threading.py", line 932, in _bootstrap_inner
  File "threading.py", line 870, in run
  File "tool.py", line 3025, in close_
  File "tool.py", line 2000, in __init__
  File "tool.py", line 2079, in start_
  File "tool.py", line 147, in call_func
  File "tool.py", line 2246, in packrom
  File "tool.py", line 147, in call_func
  File "tool.py", line 1973, in dboot
FileExistsError: [WinError 183] 当文件已存在时，无法创建该文件。: 'D:\\Ubuntu\\MIO-KITCHEN\\Elish_pipa_port\\vendor_boot\\new-boot.img' -> 'D:\\Ubuntu\\MIO-KITCHEN\\Elish_pipa_port\\\\boot.img'

**Comment by ColdWindScholar** [comment]
fixed , see https://github.com/ColdWindScholar/MIO-KITCHEN-SOURCE/commit/915e11f32d5bbcb621d0b9b25196f53637c3e952

**Comment by ColdWindScholar** [comment]
it will be fix in 3.5.9
