### ISSUE TITLE
解包payload.bin，多选报错

### ISSUE THREAD

**Issue by ymdzq** [ColdWindScholar/MIO-KITCHEN-SOURCE#46]
Exception in thread Thread-4:
Traceback (most recent call last):
  File "tool.py", line 2418, in unpack
  File "dumper.py", line 71, in run
MemoryError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "threading.py", line 932, in _bootstrap_inner
  File "threading.py", line 870, in run
  File "tool.py", line 3022, in close_
  File "tool.py", line 147, in call_func
  File "tool.py", line 2429, in unpack
  File "dumper.py", line 83, in run
  File "dumper.py", line 87, in multiprocess_partitions
  File "dumper.py", line 87, in <dictcomp>
  File "concurrent\futures\thread.py", line 188, in submit
  File "concurrent\futures\thread.py", line 213, in _adjust_thread_count
  File "threading.py", line 852, in start
RuntimeError: can't start new thread

**Comment by ColdWindScholar** [comment]
fixed, see https://github.com/ColdWindScholar/MIO-KITCHEN-SOURCE/commit/d89f0491e072b58ac0cebd0feb843f89983f8448
