### ISSUE TITLE
Program crashing wen open

### ISSUE THREAD

**Issue by starlord66** [ColdWindScholar/MIO-KITCHEN-SOURCE#61]
Exception in thread Thread-1:
Traceback (most recent call last):
  File "threading.py", line 932, in _bootstrap_inner
  File "threading.py", line 870, in run
  File "tool.py", line 1655, in list_pls
  File "PIL\ImageTk.py", line 126, in __init__
  File "tkinter\__init__.py", line 4064, in __init__
  File "tkinter\__init__.py", line 4009, in __init__
RuntimeError: main thread is not in main loop

**Comment by ColdWindScholar** [comment]
We Fixed it on next version
