### ISSUE TITLE
error the app requested i report it 

### ISSUE THREAD

**Issue by johnsonduglaus** [ColdWindScholar/MIO-KITCHEN-SOURCE#93]
Exception in thread Thread-12:
Traceback (most recent call last):
  File "threading.py", line 932, in _bootstrap_inner
  File "threading.py", line 870, in run
  File "tool.py", line 3356, in unpackrom
  File "tool.py", line 1241, in re_folder
FileExistsError: [WinError 183] Cannot create a file when that file already exists: 'C:/Users/1perc/Downloads/MIO-KITCHEN-3.9.9-win/HOME_CSC_OYN_A135UOYNBEXK1_QB88236821_REV00_user_low_ship_MULTI_CERT.tar/'

**Comment by ColdWindScholar** [comment]
give me the file

**Comment by ColdWindScholar** [comment]
Sorry, if No File the issue will close by me
